### ISSUE TITLE
Problems with django_debug_toolbar

### ISSUE THREAD

**Issue by jacobvalenta** [treyhunner/django-simple-history#139]
I am not really sure what is going on here, since I haven't fully looked into the code bases of Simple History or Debug Toolbar.

I got this stack trace when trying to import my apps/models from a separate (from my project) script (`import.py`); I was using the Django ORM to manipulate records. This was the stack track when I tried to run the script. It worked fine after I removed the HistoricalRecord from my model, or disabled the debug toolbar

```
Traceback (most recent call last):
  File "import.py", line 35, in <module>
    main(sys.argv[1:])
  File "import.py", line 32, in main
    CPImporter(client, file_to_import)
  File "/Users/jacob/Documents/Github/pawnmetrics-importers/pmimporter2/cp.py", line 36, in __init__
    self.client, created = Client.objects.get_or_create(name=client_name, subdomain=client_name)
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/db/models/manager.py", line 154, in get_or_create
    return self.get_queryset().get_or_create(**kwargs)
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/db/models/query.py", line 376, in get_or_create
    return self.get(**lookup), False
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/db/models/query.py", line 301, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/db/models/query.py", line 593, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/db/models/query.py", line 611, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1204, in add_q
    clause = self._add_q(where_part, used_aliases)
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1240, in _add_q
    current_negated=current_negated)
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1103, in build_filter
    allow_explicit_fk=True)
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1363, in setup_joins
    names, opts, allow_many, allow_explicit_fk)
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1271, in names_to_path
    field, model, direct, m2m = opts.get_field_by_name(name)
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/db/models/options.py", line 373, in get_field_by_name
    cache = self.init_name_map()
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/db/models/options.py", line 402, in init_name_map
    for f, model in self.get_all_related_m2m_objects_with_model():
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/db/models/options.py", line 518, in get_all_related_m2m_objects_with_model
    cache = self._fill_related_many_to_many_cache()
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/db/models/options.py", line 532, in _fill_related_many_to_many_cache
    for klass in get_models(only_installed=False):
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/db/models/loading.py", line 232, in get_models
    self._populate()
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/debug_toolbar/models.py", line 9, in <module>
    dt_settings.patch_all()
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/debug_toolbar/settings.py", line 215, in patch_all
    patch_root_urlconf()
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/debug_toolbar/settings.py", line 203, in patch_root_urlconf
    reverse('djdt:render_panel')
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/core/urlresolvers.py", line 503, in reverse
    app_list = resolver.app_dict[ns]
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/core/urlresolvers.py", line 329, in app_dict
    self._populate()
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/core/urlresolvers.py", line 267, in _populate
    for pattern in reversed(self.url_patterns):
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/jacob/.virtualenvs/pawnmetrics/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "../mercury2/mercury2/urls.py", line 11, in <module>
    from mercury2.gun_log.views import GunLogEntryViewSet
  File "../mercury2/mercury2/gun_log/views.py", line 14, in <module>
    class GunLogEntryViewSet(viewsets.ModelViewSet):
  File "../mercury2/mercury2/gun_log/views.py", line 15, in GunLogEntryViewSet
    model = GunLogEntry
NameError: name 'GunLogEntry' is not defined
```

**Comment by macro1** [comment]
I'm guessing this resolved, closing.

**Comment by jacobvalenta** [comment]
I actually just got around to rewriting it, and a management command solved it.
