### ISSUE TITLE
simple history and migrations in django 1.7

### ISSUE THREAD

**Issue by glato** [treyhunner/django-simple-history#146]
During a django project migration from 1.6.x to 1.7.1, I've run into a problem with

django-simple-history==1.5.3

and

Django==1.7.1

since I am not able to do a simple "manage.py syncdb“ anymore, e. g.

$ ./manage.py syncdb
Operations to perform:
  Synchronize unmigrated apps: django_summernote, django_admin_bootstrapped, simple_history, guardian, silogapi, sinews, debug_toolbar, widget_tweaks, sicore, siwiki, django_extensions, simonitoring, sidublincore, rest_framework, sineurolex, sidataupload, dajaxice
  Apply all migrations: admin, contenttypes, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 27, in handle_noargs
    call_command("migrate", **options)
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 155, in handle
    changes = autodetector.changes(graph=executor.loader.graph)
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 42, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 110, in _detect_changes
    self.new_apps = self.to_state.render()
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/django/db/migrations/state.py", line 67, in render
    model.render(self.apps)
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/django/db/migrations/state.py", line 312, in render
    body,
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/django/db/models/base.py", line 284, in __new__
    new_class._prepare()
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/django/db/models/base.py", line 344, in _prepare
    signals.class_prepared.send(sender=cls)
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/django/db/models/fields/related.py", line 93, in do_pending_lookups
    operation(field, sender, cls)
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/django/db/models/fields/related.py", line 271, in resolve_related_class
    field.do_related_class(model, cls)
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/simple_history/models.py", line 296, in do_related_class
    field = self.get_field(other, cls)
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/simple_history/models.py", line 261, in get_field
    field = self.get_one_to_one_field(to_field, other)
  File "/Users/latog/.virtualenvs/si/lib/python2.7/site-packages/simple_history/models.py", line 246, in get_one_to_one_field
    temp_field = self.__class__(to_field.rel.to._meta.object_name)
AttributeError: 'unicode' object has no attribute '_meta'

I am using python 2.7.5 and sqlite3 as backend, do you have any hint?

Thanks in advance!

Grzegorz

**Comment by macro1** [comment]
This has probably been resolved by switching away from our custom `CustomForeignKeyField`. Closing.
