### ISSUE TITLE
IntegrityError when deleting User with email set to None

### ISSUE THREAD

**Issue by hakanb** [treyhunner/django-simple-history#188]
I'm getting the following error when trying to delete a User model with the email field set to `None`:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/hakan/Sites/.virtualenvs/djtest/lib/python2.7/site-packages/django/db/models/base.py", line 872, in delete
    collector.delete()
  File "/Users/hakan/Sites/.virtualenvs/djtest/lib/python2.7/site-packages/django/db/models/deletion.py", line 314, in delete
    sender=model, instance=obj, using=self.using
  File "/Users/hakan/Sites/.virtualenvs/djtest/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/hakan/Sites/.virtualenvs/djtest/lib/python2.7/site-packages/simple_history/models.py", line 229, in post_delete
    self.create_historical_record(instance, '-')
  File "/Users/hakan/Sites/.virtualenvs/djtest/lib/python2.7/site-packages/simple_history/models.py", line 239, in create_historical_record
    history_user=history_user, **attrs)
  File "/Users/hakan/Sites/.virtualenvs/djtest/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/hakan/Sites/.virtualenvs/djtest/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/hakan/Sites/.virtualenvs/djtest/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/hakan/Sites/.virtualenvs/djtest/lib/python2.7/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/hakan/Sites/.virtualenvs/djtest/lib/python2.7/site-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/hakan/Sites/.virtualenvs/djtest/lib/python2.7/site-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/Users/hakan/Sites/.virtualenvs/djtest/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/hakan/Sites/.virtualenvs/djtest/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/hakan/Sites/.virtualenvs/djtest/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 963, in execute_sql
    cursor.execute(sql, params)
  File "/Users/hakan/Sites/.virtualenvs/djtest/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/hakan/Sites/.virtualenvs/djtest/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/hakan/Sites/.virtualenvs/djtest/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/hakan/Sites/.virtualenvs/djtest/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
IntegrityError: null value in column "email" violates not-null constraint
DETAIL:  Failing row contains (1, , null, f, user, , , null, f, t, 2015-07-30 15:15:49.870048+00, 2, 2015-07-30 15:15:55.130355+00, -, null).
```

I've confirmed that this isn't an issue with a fresh install of Django with no `django-simple-history`.

Steps to reproduce:
- Create a fresh Django project
  - `mkvirtualenv djtest`
  - `workon djtest`
  - `pip install Django==1.8`
  - `cd ~/Sites/`
  - `django-admin createproject djtest`
- Create a fresh database
  - `pip install psycopg2==2.6.1`
  - `psql template1`
    - `create database djtest;`
    - `create user djtest;`
    - `grant all privileges on djtest to djtest;`
    - `\q;`
- Add new database to `DATABASE_SETTINGS`
- Set up database
  - `cd djtest`
  - `./manage.py migrate`
- Add django-simple-history to project
  - `pip install django-simple-history==1.6.2`
  - Add `simple_history` to `INSTALLED_APPS`
- Create new app to add `HistoricalUser`
  - `cd ~/Sites/djtest/`
  - `./manage.py startapp core`
  - Register HistoricalUser in `core/models.py`:  
     ```
    from django.contrib.auth.models import User

    from simple_history import register

    register(User)
     ```
   - Add `core` to `INSTALLED_APPS`
   - `./manage.py makemigrations`
  - `./manage.py migrate`
- Create and try to delete user from shell
  - `./manage.py shell`
  - `from django.contrib.auth.models import User`
  - `u = User.objects.create(username='username', email='user@example.com')`
  - `u.email = None`
  - `u.delete()`

Tables:
```
djtest=# \d auth_user
                                     Table "public.auth_user"
    Column    |           Type           |                       Modifiers
--------------+--------------------------+--------------------------------------------------------
 id           | integer                  | not null default nextval('auth_user_id_seq'::regclass)
 password     | character varying(128)   | not null
 last_login   | timestamp with time zone |
 is_superuser | boolean                  | not null
 username     | character varying(30)    | not null
 first_name   | character varying(30)    | not null
 last_name    | character varying(30)    | not null
 email        | character varying(254)   | not null
 is_staff     | boolean                  | not null
 is_active    | boolean                  | not null
 date_joined  | timestamp with time zone | not null
Indexes:
    "auth_user_pkey" PRIMARY KEY, btree (id)

djtest=# \d auth_historicaluser;
                                          Table "public.auth_historicaluser"
     Column      |           Type           |                                Modifiers
-----------------+--------------------------+--------------------------------------------------------------------------
 id              | integer                  | not null
 password        | character varying(128)   | not null
 last_login      | timestamp with time zone |
 is_superuser    | boolean                  | not null
 username        | character varying(30)    | not null
 first_name      | character varying(30)    | not null
 last_name       | character varying(30)    | not null
 email           | character varying(254)   | not null
 is_staff        | boolean                  | not null
 is_active       | boolean                  | not null
 date_joined     | timestamp with time zone | not null
 history_id      | integer                  | not null default nextval('auth_historicaluser_history_id_seq'::regclass)
 history_date    | timestamp with time zone | not null
 history_type    | character varying(1)     | not null
 history_user_id | integer                  |
Indexes:
    "auth_historicaluser_pkey" PRIMARY KEY, btree (history_id)
    "auth_historicaluser_14c4b06b" btree (username)
    "auth_historicaluser_b80bb774" btree (id)
    "auth_historicaluser_e7d5ef68" btree (history_user_id)
    "auth_historicaluser_username_42a567c710e5839c_like" btree (username varchar_pattern_ops)
```

I'm running PostgreSQL 9.3.9:
```
djtest=# select version();
                                                                version
---------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.3.9 on x86_64-apple-darwin14.3.0, compiled by Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn), 64-bit
(1 row)
```

Any ideas? This works OK when I use `User.email=''` instead of `None` but I'd like to avoid workarounds if possible.

**Comment by macro1** [comment]
You will see a constraint failure without simple history if you set the email to None and save instead of deleteting...

```
from django.contrib.auth.models import User
u = User.objects.create(username='username', email='user@example.com')
u.email = None
u.save()
```

Simple history saves a copy of the object when it deletes, using the current values in the instance. Without simple history, setting the email to `None` would be a no-op, it wouldn't change anything since the record will be deleted anyway. I'd suggest leaving the email intact till the delete completes, or using a custom user model with a nullable email field.

**Comment by hakanb** [comment]
Interesting. I thought I had check for that and didn't see a problem, but I just retried and you're right.

Thanks for looking into this!
