### ISSUE TITLE
SSL SYSCALL error

### ISSUE THREAD

**Issue by psychok7** [treyhunner/django-simple-history#189]
Hi there so i am trying  django-simple-history + django 1.7 and i have a table with about 300.000 records. When i run `populate_history` i get an error:

```
(xxx)vagrant@vagrant:/vagrant$ python manage.py populate_history --auto --settings=xxx.settings.local
INFO 2015-07-31 14:54:39,572 base 1713 139923734366016 Raven is not configured (logging is disabled). Please see the documentation for more information.
Existing history found, skipping model <class 'support_tables.models.ParishCouncil'>
Existing history found, skipping model <class 'support_tables.models.Occupation'>
Saving historical records for <class 'support_tables.models.PostalCode'>
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/simple_history/management/commands/populate_history.py", line 61, in handle
    self._process(to_process)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/simple_history/management/commands/populate_history.py", line 106, in _process
    utils.bulk_history_create(model, history_model)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/simple_history/management/commands/_populate_utils.py", line 27, in bulk_history_create
    history_model.objects.bulk_create(historical_instances)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/db/models/query.py", line 409, in bulk_create
    self._batched_insert(objs_without_pk, fields, batch_size)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/db/models/query.py", line 938, in _batched_insert
    using=self.db)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 921, in execute_sql
    cursor.execute(sql, params)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.DatabaseError: SSL SYSCALL error: EOF detected
```

Any ideas? Is this because of the number of entries i have? i am using a machine with single core and 2GB

**Comment by macro1** [comment]
@psychok7, what DB service are you using?

**Comment by psychok7** [comment]
@macro1 i am using PostgreSQL 9.3

**Comment by macro1** [comment]
A little googling says it's a generic connection error which could be raised by a timeout, so the amount of data may be the issue. In the short term you can look at [the code for the management command](https://github.com/treyhunner/django-simple-history/blob/1.6.3/simple_history/management/commands/populate_history.py) and modify it to paginate and add it to one of your own apps.

If you have time, we could probably add a batch size to the command that would allow it to build the initial history layer in chunks. Currently the command would do all 300,000 entries in one query, which is probably not a great idea.
