### ISSUE TITLE
I try usage in Django 1.10.2 and I am seeing error in runserver

### ISSUE THREAD

**Issue by lukasgarcya** [treyhunner/django-simple-history#241]
In my project I'm using Django 1.10 and when I run runserver does not work due to the error below:

Unhandled exception in thread started by <function wrapper at 0x7f2211a89668>
Traceback (most recent call last):
  File "/home/lukasgarcya/.virtualenvs/django_atual/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(_args, *_kwargs)
  File "/home/lukasgarcya/.virtualenvs/django_atual/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 142, in inner_run
    handler = self.get_handler(_args, *_options)
  File "/home/lukasgarcya/.virtualenvs/django_atual/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super(Command, self).get_handler(_args, *_options)
  File "/home/lukasgarcya/.virtualenvs/django_atual/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/home/lukasgarcya/.virtualenvs/django_atual/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 49, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/lukasgarcya/.virtualenvs/django_atual/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/lib64/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/home/lukasgarcya/workspace/django_atual/django_atual/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/lukasgarcya/.virtualenvs/django_atual/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/home/lukasgarcya/.virtualenvs/django_atual/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 153, in **init**
    self.load_middleware()
  File "/home/lukasgarcya/.virtualenvs/django_atual/lib/python2.7/site-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters

**Comment by nessalc** [comment]
This is the same issue as #234, I believe. django-simple-history is not yet compatible with version 1.10.X.

**Comment by lukasgarcya** [comment]
Do you have any estimate of when you will have support for version of Django 1.10.x?

**Comment by lukasgarcya** [comment]
I have an solution.

**Comment by lukasgarcya** [comment]
My solution:
from . models import HistoricalRecords
from django.utils.deprecation import MiddlewareMixin

class HistoryRequestMiddleware(MiddlewareMixin):
    """Expose request to HistoricalRecords.

    This middleware sets request as a local thread variable, making it
    available to the model-level utilities to allow tracking of the
    authenticated user making a change.
    """

    def __init__(self, get_response):
        self.get_response = get_response
        
    def __call__(self, request):
	HistoricalRecords.thread.request = request
	if hasattr(HistoricalRecords.thread, 'request'):
            del HistoricalRecords.thread.request            
	response = self.get_response(request)
        return response

But not working in Django <1.10

**Comment by macro1** [comment]
As noted, there wasn't support for Django 1.10. Support has been added to master, it will be released shortly.
