### ISSUE TITLE
Django 1.10 populate_history

### ISSUE THREAD

**Issue by icygithub** [treyhunner/django-simple-history#262]
python manage.py populate_history --auto
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DIRS.
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/trusty/django/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/trusty/django/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/trusty/django/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/trusty/django/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/trusty/django/local/lib/python2.7/site-packages/simple_history/management/commands/populate_history.py", line 68, in handle
    self._process(to_process)
  File "/home/trusty/django/local/lib/python2.7/site-packages/simple_history/management/commands/populate_history.py", line 106, in _process
    if history_model.objects.count():
  File "/home/trusty/django/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/trusty/django/local/lib/python2.7/site-packages/django/db/models/query.py", line 369, in count
    return self.query.get_count(using=self.db)
  File "/home/trusty/django/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 476, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/home/trusty/django/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 457, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/trusty/django/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/home/trusty/django/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/trusty/django/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/trusty/django/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/trusty/django/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/trusty/django/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/home/trusty/django/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/trusty/django/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.ProgrammingError: (1146, "Table 'mydjango.pyfyp_historicalaccidents' doesn't exist")

**Comment by macro1** [comment]
As the error message says, the table doesn't exist. Registering a model to have its history tracked will define a shadow model which will need to be added to your migrations. So, [makemigrations](https://docs.djangoproject.com/en/1.10/ref/django-admin/#makemigrations), and [migrate](https://docs.djangoproject.com/en/1.10/ref/django-admin/#migrate), and your DB should be updated with the new shadow tables.

**Comment by icygithub** [comment]
You are absolutely right 😊 
Thank you

**Comment by ukrutt** [comment]
The need to do `makemigrations` is actually not listed in the docs... and tripped me up until I found this.  It would be helpful to have a note about this in the Quick Start, maybe right after the [models section](https://django-simple-history.readthedocs.io/en/latest/usage.html#models).  (Yes, in hindsight it's obvious...)
