### ISSUE TITLE
No module named reportssimple_history

### ISSUE THREAD

**Issue by joaopaulo164** [treyhunner/django-simple-history#270]
When I try to run makemirations I'm having this problem:

(executiveENV) joao@joao-VirtualBox:~/projetos/executive_backend$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/joao/projetos/executiveENV/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/joao/projetos/executiveENV/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/joao/projetos/executiveENV/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/joao/projetos/executiveENV/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/joao/projetos/executiveENV/local/lib/python2.7/site-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named reportssimple_history

**Comment by joaopaulo164** [comment]
Sorry guys... It was my mistake:

INSTALLED_APPS = (
    # othes
    'reports'        **<====== I forgot the comma here**
    'simple_history'
)
