### ISSUE TITLE
Django 2.0 compatibility

### ISSUE THREAD

**Issue by brot** [treyhunner/django-simple-history#330]
I try to update my website to Django 2.0 and got an error for **simple_history/models.py**

```
  File "/home/bernd/.local/share/virtualenvs/bit-a8MytMjT/lib/python3.5/site-packages/django/db/models/base.py", line 308, in __new__
    new_class._prepare()
  File "/home/bernd/.local/share/virtualenvs/bit-a8MytMjT/lib/python3.5/site-packages/django/db/models/base.py", line 363, in _prepare
    class_prepared.send(sender=cls)
  File "/home/bernd/.local/share/virtualenvs/bit-a8MytMjT/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 178, in send
    for receiver in self._live_receivers(sender)
  File "/home/bernd/.local/share/virtualenvs/bit-a8MytMjT/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/bernd/.local/share/virtualenvs/bit-a8MytMjT/lib/python3.5/site-packages/simple_history/models.py", line 94, in finalize
    history_model = self.create_history_model(sender)
  File "/home/bernd/.local/share/virtualenvs/bit-a8MytMjT/lib/python3.5/site-packages/simple_history/models.py", line 129, in create_history_model
    fields = self.copy_fields(model)
  File "/home/bernd/.local/share/virtualenvs/bit-a8MytMjT/lib/python3.5/site-packages/simple_history/models.py", line 176, in copy_fields
    old_field.rel.to,
AttributeError: 'ForeignKey' object has no attribute 'rel'
```

**Comment by hangya** [comment]
#320 also addresses this - I hope it will be merged in the near future

**Comment by whoisearth** [comment]
Just got this too after upgrade :)

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.2.3\helpers\pycharm\django_manage.py", line 43, in <module>
    run_module(manage_file, None, '__main__', True)
  File "D:\Python35\lib\runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "D:\Python35\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:/Projects/enterpass/api\manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "D:\Python35\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "D:\Python35\lib\site-packages\django\core\management\__init__.py", line 347, in execute
    django.setup()
  File "D:\Python35\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\Python35\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "D:\Python35\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "D:\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "D:/Projects/enterpass/api\passwords\models.py", line 3, in <module>
    from passwordfolders.models import PasswordFolder
  File "D:/Projects/enterpass/api\passwordfolders\models.py", line 31, in <module>
    register(PasswordFolder, table_name='enterpass_passwordfolderhistory')
  File "D:\Python35\lib\site-packages\simple_history\__init__.py", line 33, in register
    records.finalize(model)
  File "D:\Python35\lib\site-packages\simple_history\models.py", line 90, in finalize
    history_model = self.create_history_model(sender)
  File "D:\Python35\lib\site-packages\simple_history\models.py", line 125, in create_history_model
    fields = self.copy_fields(model)
  File "D:\Python35\lib\site-packages\simple_history\models.py", line 165, in copy_fields
    old_field.rel.to,
AttributeError: 'ForeignKey' object has no attribute 'rel'

**Comment by Bernix01** [comment]
any update on this?

**Comment by Sharpek** [comment]
+1

**Comment by mrzorn** [comment]
+1

Any idea when this will be addressed?

**Comment by rsd** [comment]
+1

**Comment by rsd** [comment]
Is this project abandonware?

**Comment by kennell** [comment]
+1

**Comment by wontonst** [comment]
+1

**Comment by avalanchy** [comment]
I am working on a branch `django-20` for couple of days and had no trouble under Django 2.

**Comment by jhrr** [comment]
Yep, really needing this upgrade right now...

**Comment by jhrr** [comment]
There's an active PR [here](https://github.com/treyhunner/django-simple-history/pull/320) in case anyone is looking for unblockage.

**Comment by kennell** [comment]
I can vouch for the `django-20` branch, working without any problems so far.

**Comment by rsd** [comment]
This is working for me so far:
` pip install -e git+https://github.com/treyhunner/django-simple-history.git@django-20#egg=django-simple-history`

**Comment by andytwoods** [comment]
Couldnt get rsd's command to work on Windows. This worked for me 
pip install https://github.com/treyhunner/django-simple-history/archive/django2.0.zip

**Comment by 1988gadocansey** [comment]
Excellent fix

**Comment by rossmechanic** [comment]
Master now supports Django 2.0. Will be releasing soon.

**Comment by rossmechanic** [comment]
Django 2.0 support has been released!
