### ISSUE TITLE
AttributeError when using historical querysets with Django REST framework

### ISSUE THREAD

**Issue by dgilge** [treyhunner/django-simple-history#332]
We are building an API where you can retreive the history, too. Now I get `AttributeError: 'HistoryManager' object has no attribute '_meta'`.

This feature is essential for us. Therefore I'm really interested in a solution.

[Here](https://github.com/dgilge/test_simple_history) is a test repository. Run `$ ./manage.py test myapp` and you will get:

```
Traceback (most recent call last):
  File "/Users/Daniel/django/test_simple_history/myapp/tests.py", line 12, in test_historical_manager_works_with_drf
    response = self.client.get('/testurl/')
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/django/test/client.py", line 529, in get
    **extra)
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/django/test/client.py", line 333, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/django/test/client.py", line 409, in generic
    return self.request(**r)
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/django/test/client.py", line 494, in request
    six.reraise(*exc_info)
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/django/utils/six.py", line 686, in reraise
    raise value
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/rest_framework/viewsets.py", line 90, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/rest_framework/mixins.py", line 48, in list
    return Response(serializer.data)
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/rest_framework/serializers.py", line 738, in data
    ret = super(ListSerializer, self).data
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/rest_framework/serializers.py", line 656, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/rest_framework/serializers.py", line 656, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/rest_framework/serializers.py", line 483, in to_representation
    fields = self._readable_fields
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/rest_framework/serializers.py", line 377, in _readable_fields
    field for field in self.fields.values()
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/rest_framework/serializers.py", line 363, in fields
    for key, value in self.get_fields().items():
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/rest_framework/serializers.py", line 992, in get_fields
    info = model_meta.get_field_info(model)
  File "/Users/Daniel/venv/test_simple_history/lib/python3.5/site-packages/rest_framework/utils/model_meta.py", line 35, in get_field_info
    opts = model._meta.concrete_model._meta
AttributeError: 'HistoryManager' object has no attribute '_meta'
```

**Comment by rossmechanic** [comment]
@dgilge This is an issue with how you set the `model` field in your TestSerializer. You wrote:
```
class TestSerializer(serializers.ModelSerializer):
    class Meta:
        model = models.TestModel.history
        fields = '__all__'
```
But models.TestModel.history refers to the `HistoryManager` as opposed to the actual model. If you change that line to `model= models.TestModel.history.model` it'll pass your tests.

**Comment by dgilge** [comment]
Thanks for your very quick reply and solution! Can we explain that in the docs somewhere?

**Comment by rossmechanic** [comment]
Fine with me but I don't have edit rights

**Comment by rossmechanic** [comment]
@dgilge I'm now a maintainer on the library. Feel free to put up a PR with this documentation addition and I'll merge it.
