### ISSUE TITLE
invalid literal for int() with base 10: 'a string' when using hashid fields.

### ISSUE THREAD

**Issue by spyoungtech** [treyhunner/django-simple-history#337]
I just ran into this issue using v 1.9.0 -- Just like #182 

I'm using a `HashidAutoField` from [django-hashid-field](https://github.com/nshafer/django-hashid-field)  with my models. This seems to still confuse simple-history in the same way.

For example... a profile model
```python
class UserProfile(models.Model):
    id = HashidAutoField(alphabet=string.ascii_uppercase+string.digits, primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    # other fields
    history = HistoricalRecords()
```

Any ideas where I can start tracking down the cause? Looking at the PR that resolved #182 -- a cause or solution was not immediately apparent.

**Comment by rossmechanic** [comment]
Hey @spyoungtech did you ever figure this out?

**Comment by spyoungtech** [comment]
Oh boy, I wish I could remember the complete context around this or the complete steps to reproduce. I am a doofus for not including the entire stack trace.

If memory serves, [models.py L418](https://github.com/treyhunner/django-simple-history/blob/9e95fd8093356986c2eff36247a275fce0c1c3d9/simple_history/models.py#L418) may have been part of the issue.

The HashidAutoField is happy to accept strings, and while under the hood, IntegerField was OK for representation in the DB, caused some issues in migration because the field would return as a string on the original model.


However, I just tried reproducing on latest versions of both packages and either the steps I'm taking are different or the problem may have been solved. Not sure, but will look into it more this weekend.

**Comment by legshort** [comment]
@spyoungtech This is my quick solution, perhaps not for best one cuz I'm pretty sure there is a decode method from `hashidfield` library that converts from str hash code to internal int value but I haven't seen any code working like that at a glance.

```python
class HashIdFieldAdminMixin:
    def _decode_id(self, model, object_id):
        obj = model.objects.all_with_deleted().get(id=object_id)
        decoded_id = str(obj.id.id)

        return decoded_id

    def history_view(self, request, object_id, extra_context=None):
        decoded_id = self._decode_id(self.model, object_id)

        return super().history_view(request, decoded_id, extra_context=extra_context)

    def history_form_view(self, request, object_id, version_id):
        decoded_id = self._decode_id(self.model, object_id)

        return super().history_form_view(request, decoded_id, version_id)
```

**Comment by legshort** [comment]
I kind of found `decoding` method from the library but didn't seem the elegant way to do it but anyway I updated the above code like this.
At least this way doen't require to run a query.

```python
    def _decode_id(self, model, object_id):
        decoded_id = str(model(id=0).decode(object_id))

        return decoded_id
```

**Comment by spyoungtech** [comment]
Sadly, I haven't been able to figure out how to reproduce, even on 1.9.0 (and relevant version of django-hashid-field)
The project in which I originally had this issue belongs to a company I'm no longer with.

If anyone can provide discrete steps to reproduce, I'd be happy to give that another go.

**Comment by rossmechanic** [comment]
Thanks for looking into this @spyoungtech ! Going to close out this issue. If someone else runs into it, we can reopen and reevaluate.

**Comment by timur-orudzhov** [comment]
This issue still exists. I've also run into this, when I'm trying to open history page in admin. I think problem with **object_id**, as pk of model I have some string which is not acceptable by django-simple-history.

Traceback:

```
Traceback (most recent call last):
  File "/Users/timur/projects/muslim_dating/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/timur/projects/muslim_dating/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/timur/projects/muslim_dating/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/timur/projects/muslim_dating/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/timur/projects/muslim_dating/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/timur/projects/muslim_dating/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/timur/projects/muslim_dating/venv/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/Users/timur/projects/muslim_dating/venv/lib/python3.7/site-packages/simple_history/admin.py", line 53, in history_view
    action_list = history.filter(**{pk_name: object_id})
  File "/Users/timur/projects/muslim_dating/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/timur/projects/muslim_dating/venv/lib/python3.7/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/timur/projects/muslim_dating/venv/lib/python3.7/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/timur/projects/muslim_dating/venv/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/timur/projects/muslim_dating/venv/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/Users/timur/projects/muslim_dating/venv/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/timur/projects/muslim_dating/venv/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1116, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/Users/timur/projects/muslim_dating/venv/lib/python3.7/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/timur/projects/muslim_dating/venv/lib/python3.7/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/timur/projects/muslim_dating/venv/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 1819, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1NjoeRX'
2019-09-07 11:50:43 [ERROR] "GET /admin/users/userprofile/1NjoeRX/history/ HTTP/1.1" 500 138229
```

Versions: django-hashid-field==2.1.6, django-simple-history==2.7.3.

**Comment by neversay4ever** [comment]
django2.2.10 still has this issue. I use django-import-export to import data in admin, and get this error.

**Comment by felixschloesser** [comment]
any news on this?

**Comment by jpnadas** [comment]
Not sure if this is still relevant for you @felixschloesser, but for anyone finding this in the future. [The answer ](https://github.com/jazzband/django-simple-history/issues/337#issuecomment-445617450) given by @legshort solves it.

Just make sure to add the defined mixin before the SimpleAdminHistory in your admin model, and you are good to go. 

For example, considering that `Poll` has a `HashidAutoField` for its `id`, we can define in `admin.py`:

```python
class HashIdFieldAdminMixin:
    def _decode_id(self, model, object_id):
        obj = model.objects.get(id=object_id)
        decoded_id = str(obj.id.id)

        return decoded_id

    def history_view(self, request, object_id, extra_context=None):
        decoded_id = self._decode_id(self.model, object_id)

        return super().history_view(request, decoded_id, extra_context=extra_context)

    def history_form_view(self, request, object_id, version_id):
        decoded_id = self._decode_id(self.model, object_id)

        return super().history_form_view(request, decoded_id, version_id)


@admin.register(models.Poll)
class PollAdmin(HashIdFieldAdminMixin, SimpleHistoryAdmin):
    list_display = ["id", "name", "status"]
    history_list_display = ["status"]
```

**Comment by jpnadas** [comment]
@rossmechanic do you think it is worth including the aforementioned mixin into the project? I can make a PR if you deem it a good idea.
