### ISSUE TITLE
ModuleNotFoundError: No module named 'django.core.urlresolvers'

### ISSUE THREAD

**Issue by sadaf2605** [treyhunner/django-simple-history#359]
I am using <code>django 2.0.1</code on <code>python 3.6.3</code>. When I tried to migrate:

<pre>
(evaly3.6.3) Mds-MacBook-Pro:evaly sadafnoor$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/Users/sadafnoor/.pyenv/versions/3.6.3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/simple_history/admin.py", line 9, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
(evaly3.6.3) Mds-MacBook-Pro:evaly sadafnoor$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/Users/sadafnoor/.pyenv/versions/3.6.3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/simple_history/admin.py", line 9, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
</pre>

**Comment by rossmechanic** [comment]
@sadaf2605  simple-history doesn't have support for Django2.0 yet, but there will be a release this week with Django2.0 support. In the meantime, look at #330 for the branch you should use for 2.0 support.
