### ISSUE TITLE
On migrate Error: ImportError: No module named 'django.urls'

### ISSUE THREAD

**Issue by shubhamxaio** [treyhunner/django-simple-history#375]
I'm working on Django 1.8. I have installed the django-simple-history using **pip** in virtualenv. I have configured in installed apps as well as in Middleware.
After that I'm trying to migrate but it is throwing error:

```
(mdnenv)$ python manage.py migrarte

Traceback (most recent call last):
  File "./manage.py", line 4, in <module>
    from settings.base import DJANGO_SETTINGS_MODULE
  File "/home/shubham/mdn_project/mdn-core-engine-development/settings/__init__.py", line 1, in <module>
    from settings.base import *
  File "/home/shubham/mdn_project/mdn-core-engine-development/settings/base.py", line 184, in <module>
    from mdn_core_engine.logger import logger
  File "/home/shubham/mdn_project/mdn-core-engine-development/mdn_core_engine/__init__.py", line 2, in <module>
    from .celery import app as celery_app
  File "/home/shubham/mdn_project/mdn-core-engine-development/mdn_core_engine/celery.py", line 13, in <module>
    django.setup()
  File "/home/shubham/mdn_project/mdnenv/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/shubham/mdn_project/mdnenv/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/shubham/mdn_project/mdnenv/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/shubham/mdn_project/mdnenv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/shubham/mdn_project/mdnenv/lib/python3.4/site-packages/simple_history/models.py", line 12, in <module>
    from django.urls import reverse
ImportError: No module named 'django.urls'
```

**Comment by rossmechanic** [comment]
django-simple-history 2.0 doesn't support Django<1.11. The last version of django-simple-history to support Django 1.8 is django-simple-history==1.9.1. So run this command and it should work:
```
pip install django-simple-history==1.9.1
```

**Comment by shubhamxaio** [comment]
Thanks... It's working now...
