### ISSUE TITLE
Problem to use history = HistoricalRecords(excluded_fields=['description'])

### ISSUE THREAD

**Issue by eliUni** [treyhunner/django-simple-history#402]
I would like to exclude some fields of the model.

I use the following to exclude a field to the model:
```
class Metabolite(BaseModel):
    met_id = models.AutoField(primary_key=True, db_column="met_id")
    abbreviation = models.CharField(max_length=250, db_index=True, help_text="Unique metabolite identifier")
    fullName = models.TextField(help_text="Name of the metabolite")
    description = models.TextField(null=True, help_text="Description of metabolite in HMDB", blank=True)
    history = HistoricalRecords(excluded_fields=['description'])
```
I made makemigrations
Following file created:
 operations = [
        migrations.RemoveField(
            model_name='historicalmetabolite',
            name='description',
        ),
I run the migration
And when I run python manage.py populate_history --auto
I add the following mistake:

Saving historical records for <class 'reconws.models.Metabolite'>
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/srv/venv/local/lib/python2.7/site-packages/simple_history/management/commands/populate_history.py", line 65, in handle
    self._process(to_process, batch_size=options['batchsize'])
  File "/srv/venv/local/lib/python2.7/site-packages/simple_history/management/commands/populate_history.py", line 110, in _process
    utils.bulk_history_create(model, history_model, batch_size)
  File "/srv/venv/local/lib/python2.7/site-packages/simple_history/management/commands/_populate_utils.py", line 28, in bulk_history_create
    ) for instance in model.objects.all()]
  File "/srv/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 572, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'description' is an invalid keyword argument for this function

```

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Django Simple History Version: django-simple-history==2.0
 - Django Version: Django==1.11.10

**Additional context**

**Comment by rossmechanic** [comment]
Hey @eliUni thanks for submitting this bug. We have a PR open for this fix (#381) that we're going to merge soon that addresses it, but you can look at that branch for an interim workaround. Will comment on this issue when the PR is merged, and when the merge is included in a new release.

**Comment by eliUni** [comment]
When do you thing the merge will be included in the new release?

**Comment by rossmechanic** [comment]
Going to try to get that PR merged today. Probably have a release with it in the next week or two @eliUni

**Comment by rossmechanic** [comment]
Sorry thought this was about #355 which I will merge today. I will get the fix for this bug before the next release in ~2 weeks

**Comment by rossmechanic** [comment]
Hi @eliUni . Fixed this issue in #410 and the fix is in the latest release (2.1.1)
