### ISSUE TITLE
Admin Integration broken: ContentType matching query does not exist.

### ISSUE THREAD

**Issue by theriverman** [treyhunner/django-simple-history#532]
**Describe the bug**
Hi,
Sorry if this is a user error on my side and I'm wasting your time, but I'm completely stuck at the moment to get the admin panel working.
I could easily install and integrate **django-simple-history** into my app:
  * the middleware kicks in OK
  * records are being made
  * I can access the logs from Django Shell

... but I can't get the Django Admin/History view to work.

**To Reproduce**
1. Go to `http://127.0.0.1:8000/myapp/admin/ASD/asd/1/change/`
2. Click on '**History** in the top-right corner '
3. See error

**Expected behavior**
See the history of changes as shown in the documentation [over here](https://django-simple-history.readthedocs.io/en/2.7.0/admin.html)

**Screenshots**
N/A

**Environment:**
 - OS: Windows 10
 - Browser (if applicable): Firefox 65.0.2
 - Django Simple History Version: 2.7.0
 - Django Version: 2.1.5
 - Database Version: SQLite (development) | PostgreSQL (production - hadn't tested yet)

**Additional context**
### django-simple-history works OK:
```
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from ASD.models import ASD
>>> e = ASD.objects.get(pk=1)
>>> e.history.all()
<QuerySet [<HistoricalASD: John Appleseed (s12345) | 2019-03-20 as of 2019-03-02 17:15:22.610706+00:00>, <HistoricalASD: The Administrator (admin) | 2019-02-27 as of 2019-03-02 17:14:14.612195+00:00>]>
```
### Traceback thrown on Django Admin/History view
(couple of applications have been removed for brevity and sensitive data have been obfuscated)
```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/myapp/admin/ASD/asd/1/history/

Django Version: 2.1.5
Python Version: 3.6.7
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'simple_history',
 'ASD.apps.AsdConfig',
 'django_extensions']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'simple_history.middleware.HistoryRequestMiddleware']



Traceback:

File "C:\Users\theriverman\.virtualenvs\myapp-back-1wJT2xkN\lib\site-packages\django\contrib\contenttypes\models.py" in get_by_natural_key
  19.             ct = self._cache[self.db][(app_label, model)]

During handling of the above exception (('authsystem', 'user')), another exception occurred:

File "C:\Users\theriverman\.virtualenvs\myapp-back-1wJT2xkN\lib\site-packages\django\core\handlers\exception.py" in inner
  34.             response = get_response(request)

File "C:\Users\theriverman\.virtualenvs\myapp-back-1wJT2xkN\lib\site-packages\django\core\handlers\base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)

File "C:\Users\theriverman\.virtualenvs\myapp-back-1wJT2xkN\lib\site-packages\django\core\handlers\base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "C:\Users\theriverman\.virtualenvs\myapp-back-1wJT2xkN\lib\site-packages\django\contrib\admin\options.py" in wrapper
  604.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "C:\Users\theriverman\.virtualenvs\myapp-back-1wJT2xkN\lib\site-packages\django\utils\decorators.py" in _wrapped_view
  142.                     response = view_func(request, *args, **kwargs)

File "C:\Users\theriverman\.virtualenvs\myapp-back-1wJT2xkN\lib\site-packages\django\views\decorators\cache.py" in _wrapped_view_func
  44.         response = view_func(request, *args, **kwargs)

File "C:\Users\theriverman\.virtualenvs\myapp-back-1wJT2xkN\lib\site-packages\django\contrib\admin\sites.py" in inner
  223.             return view(request, *args, **kwargs)

File "C:\Users\theriverman\.virtualenvs\myapp-back-1wJT2xkN\lib\site-packages\simple_history\admin.py" in history_view
  75.         content_type = ContentType.objects.get_by_natural_key(*USER_NATURAL_KEY)

File "C:\Users\theriverman\.virtualenvs\myapp-back-1wJT2xkN\lib\site-packages\django\contrib\contenttypes\models.py" in get_by_natural_key
  21.             ct = self.get(app_label=app_label, model=model)

File "C:\Users\theriverman\.virtualenvs\myapp-back-1wJT2xkN\lib\site-packages\django\db\models\manager.py" in manager_method
  82.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "C:\Users\theriverman\.virtualenvs\myapp-back-1wJT2xkN\lib\site-packages\django\db\models\query.py" in get
  399.                 self.model._meta.object_name

Exception Type: DoesNotExist at /myapp/admin/ASD/asd/1/history/
Exception Value: ContentType matching query does not exist.
```

### admin.py

```
from django.contrib import admin
from simple_history.admin import SimpleHistoryAdmin
from .models import ASD


class AsdHistoryAdmin(SimpleHistoryAdmin):
    list_display = ['id', 'subject', 'date', 'manager', 'is_closed']
    history_list_display = ['id']
    search_fields = ['id', 'subject']

admin.site.register(ASD, PddHistoryAdmin)
```

### models.py
(Removed attribute arguments for brevity)
```
class ASD(models.Model):
    def get_tasks(self):
        return ASDSubTask.objects.filter(parent_asd=self)

    objects = models.Manager()

    # General Fields
    subject = models.ForeignKey(User, on_delete=models.CASCADE)
    manager = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    is_closed = models.BooleanField()
    description = models.TextField()
    quick_notes = models.CharField()
    followup_required = models.BooleanField()
    followup_date = models.DateField()
    tasks = property(get_tasks)

    # Misc.
    id = models.AutoField(primary_key=True, verbose_name="ID")
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    history = HistoricalRecords(verbose_name="ASD History")
```

**Comment by rossmechanic** [comment]
Looks like you're not inheriting from `SimpleHistoryAdmin` on your admin page. Let me know if that's the issue

**Comment by theriverman** [comment]
> 
> 
> Looks like you're not inheriting from `SimpleHistoryAdmin` on your admin page. Let me know if that's the issue @theriverman

Hi @rossmechanic 
I do inherit from `SimpleHistoryAdmin` or atleast I think so. If you have a look at my `admin.py` file (see in my original post) you can see I'm inheriting from there:
```
from simple_history.admin import SimpleHistoryAdmin
from .models import ASD

class AsdHistoryAdmin(SimpleHistoryAdmin):
```
Thanks!

**Comment by rossmechanic** [comment]
@theriverman I tried it locally while mimicking your setup and was able to view history through the admin. If you can give me a sample app with the error, I can help debug from there.

**Comment by theriverman** [comment]
I'll look into the possibilities of giving you a sample app - it's a private repository. In the meantime I've been playing around with my other models and they all fail at the very same part. When `SimpleHistoryAdmin.history_view()` gets to the point of assigning var `content_type` it fails with a 100% rate.
I can reproduce the issue in Django shell as well:
```
USER_NATURAL_KEY = ('authsystem', 'user')
from django.contrib.contenttypes.models import ContentType
content_type = ContentType.objects.get_by_natural_key(*USER_NATURAL_KEY)
----
django.contrib.contenttypes.models.ContentType.DoesNotExist: ContentType matching query does not exist.
```
At first I thought I'm implementing my User model incorrectly, but that's no the case. This request fails at all my models.
```
Traceback (most recent call last):
  File "C:\Users\theriverman\.virtualenvs\my-app-1wJT2xkN\lib\site-packages\django\contrib\contenttypes\models.py", line 19, in get_by_natural_key
    ct = self._cache[self.db][(app_label, model)]
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\theriverman\.virtualenvs\my-app-1wJT2xkN\lib\site-packages\django\contrib\contenttypes\models.py", line 21, in get_by_natural_key
    ct = self.get(app_label=app_label, model=model)
  File "C:\Users\theriverman\.virtualenvs\my-app-1wJT2xkN\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\theriverman\.virtualenvs\my-app-1wJT2xkN\lib\site-packages\django\db\models\query.py", line 399, in get
    self.model._meta.object_name
django.contrib.contenttypes.models.ContentType.DoesNotExist: ContentType matching query does not exist.
```

**Comment by theriverman** [comment]
One important additon, @rossmechanic 
If I monkey-patch that faulty line, it seems to be working flawlessly (I need to do further tests, but this is not a future-proof solution):
```
from django.contrib.auth import get_user_model
# content_type = ContentType.objects.get_by_natural_key(*USER_NATURAL_KEY)
content_type = ContentType.objects.get_for_model(get_user_model())
```

**Comment by rossmechanic** [comment]
Hi @theriverman. Weird – I see that you're using a custom user model, and it seems that that user model hasn't been registered in your `content_type` table, which is why the `get_by_natural_key` query fails. You can confirm this by going into your db and checking the `django_content_type` table to see that `authsystem`, `user` is missing. 

Can't figure out why `get_user_model()` would work but `USER_NATURAL_KEY` wouldn't...

**Comment by Timkemp1** [comment]
We're having the same Issue, have you found a better fix instead of monkey patching?

**Comment by theriverman** [comment]
Sorry for the late reply, haven't had the time to check things, @rossmechanic .
I'm not questioning that the root cause of this issue has something to do with `ContentTypes`, but they seem fine to me:
```
(myApp-back)  ..\Python\myApp-back>py manage.py dbshell
Trying to import local.py...
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
sqlite> .tables
AuthSystem_department
AuthSystem_groupcontact
AuthSystem_historicaldepartment
AuthSystem_historicalgroupcontact
AuthSystem_historicalrole
AuthSystem_historicalsite
AuthSystem_role
AuthSystem_site
AuthSystem_user
AuthSystem_user_groups
AuthSystem_user_user_permissions
Projects_customer
Projects_historicalcustomer
Projects_historicalmembership
Projects_historicalproject
Projects_membership
Projects_project
auth_group
auth_group_permissions
auth_permission
authtoken_token
django_admin_log
django_content_type
django_migrations
django_session
knox_authtoken
sqlite>
```
`AuthSystem` is where I have the logic for users, authentications, tokens, etc.. Therefore, my user model is `AuthSystem.models.User` which inherits from `AbstractUser`.

If I dump the ContentTypes via Django Shell, I get the same confirmation:
```
(myApp-back)  ..\Python\myApp-back>py manage.py shell
Trying to import local.py...
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.contrib.contenttypes.models import ContentType
>>> for ct in ContentType.objects.all():
...     print('Name', ct.name, '| Label', ct.app_label, '| Model', ct.model)
...
Name log entry | Label admin | Model logentry
Name permission | Label auth | Model permission
Name group | Label auth | Model group
Name content type | Label contenttypes | Model contenttype
Name session | Label sessions | Model session
Name Token | Label authtoken | Model token
Name auth token | Label knox | Model authtoken
Name Department | Label AuthSystem | Model department
Name Group Contact | Label AuthSystem | Model groupcontact
Name historical Department | Label AuthSystem | Model historicaldepartment
Name historical Group Contact | Label AuthSystem | Model historicalgroupcontact
Name historical Role | Label AuthSystem | Model historicalrole
Name historical Site | Label AuthSystem | Model historicalsite
Name Role | Label AuthSystem | Model role
Name Site | Label AuthSystem | Model site
Name User | Label AuthSystem | Model user
Name Customer | Label Projects | Model customer
Name historical Customer | Label Projects | Model historicalcustomer
Name historical Membership | Label Projects | Model historicalmembership
Name historical Project | Label Projects | Model historicalproject
Name Membership | Label Projects | Model membership
Name Project | Label Projects | Model project
>>>
```
Obviously, all my migrations are applied to the database:
```
(myApp-back)  ..\Python\myApp-back>py manage.py makemigrations
Trying to import local.py...
No changes detected

(myApp-back)  ..\Python\myApp-back>py manage.py migrate
Trying to import local.py...
Operations to perform:
  Apply all migrations: AuthSystem, Projects, admin, auth, authtoken, contenttypes, knox, sessions
Running migrations:
  No migrations to apply.

(myApp-back)  ..\Python\myApp-back>
```
If I'm testing/validating this in the wrong way, please give me hints/instructions!
Sadly no, @Timkemp1 -- still using the monkey-patched version.

**Comment by J-hanks** [comment]
I am having the Same problem.

**Comment by kodama007** [comment]
I'm currently having the same problem. Is there a fix for this?

**Comment by MatejMijoski** [comment]
I've also encountered the same problem and the reason why is that I declare all of the Django apps my project with a mix of lowercase and uppercase letters and they get registered in ContentTypes with the name attribute on the apps config class, which is the same as the app's name. For example, If I declare an `AuthApp` with a custom user class named `User` and a config class such as:
`class AuthappConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "AuthApp"
`
the ContentType object created is `app_label="AuthApp"` and `"model="user"`. So, the model name is lower case but not the app's name and `django-simple-history` defines the USER_NATURAL_KEY` by making both of names lowercase resulting in them not being found.

**Comment by MAbdurrehman1** [comment]
I'm facing the same issue. 
Do we have any update on the fix?

**Comment by rptmat57** [comment]
### I have 2 options to fix this currently:

#### 1. Replace USER_NATURAL_KEY manually

Somewhere in your code, preferably in your `AppConfig`, add this:

```python
from simple_history import admin
admin.USER_NATURAL_KEY = ("AuthApp", "user")
```

#### 2. Define UserAdmin and override function
define `UserAdmin(SimpleHistoryAdmin)` and override the `history_view(self, request, object_id, extra_context=None)` method by replacing:

```python
# content_type = self.content_type_model_cls.objects.get_by_natural_key(
#            *USER_NATURAL_KEY
#        )
content_type = self.content_type_model_cls.objects.get_for_model(get_user_model())
```

as suggested by @MAbdurrehman1 in his fork

**Comment by yamac-kurtulus** [comment]
Any plans to fix this? 

Also I am curious, why is `lower` called when getting the `USER_NATURAL_KEY`? Isn't `get_user_model` more robust?

**Comment by helmetwearer** [comment]
+1 for using get_user_model inside history_view on the admin to grab the content type for the User object. There are all the reasons to do it and I can't think of one reason not to
