### ISSUE TITLE
Historical model with "excluded_fields" causes DoesNotExist error when trying to get instance from historical record if object is deleted

### ISSUE THREAD

**Issue by yakimka** [treyhunner/django-simple-history#571]
**Describe the bug**
Historical model with "excluded_fields" causes DoesNotExist error when trying to get instance from historical record if object is deleted

**To Reproduce**
1. Create model as follows

```python
class ExampleModelWithExcludedField(models.Model):
    history = HistoricalRecords(excluded_fields=['description'])
    name = models.CharField(max_length=255)
    description = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
```
2. Run `./manage.py shell`

```
>>> obj = ExampleModelWithExcludedField.objects.create(name='name', description='desc')
>>> obj_id = obj.id
>>> obj.delete()
(1, {'simple_app.ExampleModelWithExcludedField': 1})
>>> hist_obj = HistoricalExampleModelWithExcludedField.objects.filter(id=obj_id).first()
>>> hist_obj.instance
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File ".../simple_history/models.py", line 383, in get_instance
    .values(*excluded_attnames)
  File ".../django/db/models/query.py", line 379, in get
    "%s matching query does not exist." %
simple_app.models.DoesNotExist: ExampleModelWithExcludedField matching query does not exist.
```

**Expected behavior**
I expected to get instance with default values for fields that excluded.

**Environment:**
 - OS: Ubuntu 18.04, Arch linux
 - Django Simple History Version: 2.7.2
 - Django Version: 1.11.22
 - Database Version: Sqlite3, PostgreSQL 11.4

**My repo for reproduce this error**

1. Clone the repo - https://github.com/yakimka/example-simple-history-project.git
     - Database is already present.
2. Install requirements
3. Run python manage.py shell
4. Run:

```
>>> from simple_app.models import HistoricalExampleModelWithExcludedField
>>> obj_with_excluded_fields = HistoricalExampleModelWithExcludedField.objects.filter(id=1).first()
>>> obj_with_excluded_fields.instance
```

5. See error

**Comment by wwarne** [comment]
Have the same issue
Django 2.2.3
Django Simple History Version: 2.7.2

**Comment by rossmechanic** [comment]
This is expected behavior and can be found in this line: https://github.com/treyhunner/django-simple-history/blob/master/simple_history/models.py#L376

Essentially, the `instance` call returns a base model instance of the historical model with the fields from the historical model. However, what do we do if there are excluded fields on the historical model? The decision we made was to populate those missing fields with the most current fields on the base model object. If the base model object is deleted, how would we populate those fields?

**Comment by yakimka** [comment]
But because of this, the `next_record`/`prev_record` doesn't work either.

```
>>> from simple_app.models import HistoricalExampleModelWithExcludedField                                                                                                                                                                                                        

>>> obj_with_excluded_fields = HistoricalExampleModelWithExcludedField.objects.filter(id=1).first()                                                                                                                                                                              

>>> obj_with_excluded_fields.prev_record                                                                                                                                                                                                                                         
---------------------------------------------------------------------------
DoesNotExist                              Traceback (most recent call last)

...

DoesNotExist: ExampleModelWithExcludedField matching query does not exist.
```

I propose to return the default value if the object is deleted.
Something like this:

```python
def get_instance(self):
    attrs = {
        field.attname: getattr(self, field.attname) for field in fields.values()
    }
    if self._history_excluded_fields:
        excluded_attnames_with_defaults = {
            model._meta.get_field(field).attname: model._meta.get_field(field).get_default()
            for field in self._history_excluded_fields
        }
        try:
            values = (
                model.objects.filter(pk=getattr(self, model._meta.pk.attname))
                    .values(*excluded_attnames_with_defaults.keys())
                    .get()
            )
        except ObjectDoesNotExist:
            values = excluded_attnames_with_defaults
        attrs.update(values)
    return model(**attrs)
```

**Comment by rossmechanic** [comment]
Reopening this because @yakimka convinced me

**Comment by amitassaraf** [comment]
@rossmechanic I seem to be getting this issue after adding a related_name to a history field on an existing dataset.
