### ISSUE TITLE
Add support of bulk_create_with_history for databases others to PostgreSQL

### ISSUE THREAD

**Issue by xahgmah** [treyhunner/django-simple-history#577]
**Problem Statement**
As mention at https://docs.djangoproject.com/en/2.2/ref/models/querysets/#bulk-create

> If the model’s primary key is an AutoField it does not retrieve and set the primary key attribute, as save() does, unless the database backend supports it (currently PostgreSQL).

For AutoField only PostgreSQL returns model instances with primary keys. Other DB's keep them None. That is why the next operation create history items for these items doesn't work. 

**Describe the solution you'd like**
Check if primary keys equal to None. If yes get created items with primary keys by the queries to DB. After that use those items to create history records.

**Comment by rez0n** [comment]
Hi, I wanna ask, this is been merged but I have an issue with the populating history using MySQL database.
Is it something related? Can you guys advise how to workaround that?

```
Traceback (most recent call last):
  File "/Users/dv/cut/manage.py", line 22, in <module>
    main()
  File "/Users/dv/cut/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/simple_history/management/commands/populate_history.py", line 64, in handle
    self._process(to_process, batch_size=options["batchsize"])
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/simple_history/management/commands/populate_history.py", line 171, in _process
    self._bulk_history_create(model, batch_size)
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/simple_history/management/commands/populate_history.py", line 142, in _bulk_history_create
    history.bulk_history_create(instances, batch_size=batch_size)
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/simple_history/manager.py", line 147, in bulk_history_create
    return self.model.objects.bulk_create(
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/django/db/models/query.py", line 506, in bulk_create
    returned_columns = self._batched_insert(
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/django/db/models/query.py", line 1277, in _batched_insert
    self._insert(item, fields=fields, using=self.db, ignore_conflicts=ignore_conflicts)
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql
    for sql, params in self.as_sql():
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1339, in as_sql
    value_rows = [
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1340, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1340, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1281, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/django/db/models/fields/related.py", line 971, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 823, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2389, in get_db_prep_value
    value = connection.ops.validate_autopk_value(value)
  File "/Users/dv/.local/share/virtualenvs/data-portal-DNZGDTQv/lib/python3.9/site-packages/django/db/backends/mysql/operations.py", line 236, in validate_autopk_value
    raise ValueError('The database backend does not accept 0 as a '
ValueError: The database backend does not accept 0 as a value for AutoField.
```
