### ISSUE TITLE
makemigrations error

### ISSUE THREAD

**Issue by AliYmn** [treyhunner/django-simple-history#584]
(env) ali@aliymn:~/portal-2.0$ python manage.py populate_history --auto
    /home/ali/env/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
    """)
    Traceback (most recent call last):
    File "manage.py", line 12, in <module>
        execute_from_command_line(sys.argv)
    File "/home/ali/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
        utility.execute()
    File "/home/ali/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
        django.setup()
    File "/home/ali/env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
        apps.populate(settings.INSTALLED_APPS)
    File "/home/ali/env/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
        app_config = AppConfig.create(entry)
    File "/home/ali/env/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
        module = import_module(entry)
    File "/home/ali/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'tasksimple_history'

**Comment by rossmechanic** [comment]
Not enough information here, but it looks like there's likely a typo in your code. Closing this.
